services:
  swann-form:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: swann_arts
    env_file:
      - apps/backend/.env
    networks:
    - global_private_network
    expose:
    - "8081" #web server
    - "465" #email server

networks:
  global_private_network:
    name: global_private_network