services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: swann_arts
    env_file:
      - apps/backend/.env
    networks:
    - global_private_network
    ports:
    - "8081:8081" #web server
    - "465:465" #email server

networks:
  global_private_network:
    external: true
    name: global_private_network