services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: swann_arts
    env_file:
      - apps/backend/.env
    ports:
    - "8081:8081"
    - "465:465"
